// Generated by gencpp from file project1_solution/TwoInts.msg
// DO NOT EDIT!


#ifndef PROJECT1_SOLUTION_MESSAGE_TWOINTS_H
#define PROJECT1_SOLUTION_MESSAGE_TWOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project1_solution
{
template <class ContainerAllocator>
struct TwoInts_
{
  typedef TwoInts_<ContainerAllocator> Type;

  TwoInts_()
    : a(0)
    , b(0)  {
    }
  TwoInts_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int16_t _a_type;
  _a_type a;

   typedef int16_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::project1_solution::TwoInts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project1_solution::TwoInts_<ContainerAllocator> const> ConstPtr;

}; // struct TwoInts_

typedef ::project1_solution::TwoInts_<std::allocator<void> > TwoInts;

typedef boost::shared_ptr< ::project1_solution::TwoInts > TwoIntsPtr;
typedef boost::shared_ptr< ::project1_solution::TwoInts const> TwoIntsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project1_solution::TwoInts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project1_solution::TwoInts_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::project1_solution::TwoInts_<ContainerAllocator1> & lhs, const ::project1_solution::TwoInts_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::project1_solution::TwoInts_<ContainerAllocator1> & lhs, const ::project1_solution::TwoInts_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace project1_solution

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::project1_solution::TwoInts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project1_solution::TwoInts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project1_solution::TwoInts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project1_solution::TwoInts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project1_solution::TwoInts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project1_solution::TwoInts_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project1_solution::TwoInts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e01e889cb1a7965611513515df5899bf";
  }

  static const char* value(const ::project1_solution::TwoInts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe01e889cb1a79656ULL;
  static const uint64_t static_value2 = 0x11513515df5899bfULL;
};

template<class ContainerAllocator>
struct DataType< ::project1_solution::TwoInts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project1_solution/TwoInts";
  }

  static const char* value(const ::project1_solution::TwoInts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project1_solution::TwoInts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 a\n"
"int16 b\n"
;
  }

  static const char* value(const ::project1_solution::TwoInts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project1_solution::TwoInts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TwoInts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project1_solution::TwoInts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project1_solution::TwoInts_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int16_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int16_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT1_SOLUTION_MESSAGE_TWOINTS_H
